-- Se informatiza la plantilla de empleados de una empresa.
-- Se valora los conocimientos entre 1 a 5.
-- Se pide:
-- 1. Crear la entidad relacion.
-- 2. Despues de crear el diagrama, crear la base de datos y
--    las tablas correspondientes.
-- 3. Agregar los usuarios:
--    - "Ana" con 5 en "PHP", 4 enn "JS", 5 en "PS" y en idioma "3".
--    - "Adrian" con 4 en "PHP", 4 "JS", 5 en "ME", 2 en "ingles".
--    - "Juan" con 5 en "Electronica", 2 en "ingles".
--    - "Gala" con 5 en "ingles", 5 en "frances" y 5 en "AC".
-- Mostrar:
-- 4. Todas las personas que hablan "frances".
-- 5. Los nombres de todos los empleados con conocimientos en "PS",
--    ordendado del mas experto al menos experto.
-- 6. Las habilidades de Adrian ordenadas en aquellas que es mas
--    habilidoso al menos habilidoso.  Si coinciden el puntaje de habilidades,
--    ordenar alfabeticamente.
-- 7. Los nombres de los empleados con conoc en "PHP" e "ingles", ordenados
--    de mayor a menor el nivel de "ingles".  En aquellos que coinciden,
--    se ordena por nivel de "PHP" de mayor a menor.